name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: sahayak-backend-server
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        run: |
          docker buildx build --cache-from type=gha --cache-to type=gha,mode=max -t us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/sahayak-backend-server/sahayak-backend-server:${{ github.sha }} --push .

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
              --image us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/sahayak-backend-server/sahayak-backend-server:${{ github.sha }} \
              --platform managed \
              --region ${{ env.REGION }} \
              --allow-unauthenticated \
              --set-env-vars "POSTGRES_URL=${{ secrets.POSTGRES_URL }},AUTH_SECRET=${{ secrets.AUTH_SECRET }}, BLOB_READ_WRITE_TOKEN=${{ secrets.BLOB_READ_WRITE_TOKEN }},GOOGLE_GENERATIVE_AI_API_KEY=${{ secrets.GOOGLE_GENERATIVE_AI_API_KEY }},GOOGLE_GEMINI_API_KEY=${{ secrets.GOOGLE_GEMINI_API_KEY }},NODE_ENV=production" \
              --timeout=900s
